# Generated by Django 3.2.12 on 2022-05-01 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('major', models.CharField(blank=True, max_length=60)),
                ('classification', models.CharField(choices=[('FR', 'Freshman'), ('SP', 'Sophmore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=20)),
                ('graduation', models.CharField(choices=[('1', '2015'), ('2', '2016'), ('3', '2017'), ('4', '2018'), ('5', '2019'), ('6', '2020'), ('7', '2021'), ('8', '2022')], max_length=40)),
                ('skills', models.TextField()),
                ('languages', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('picture', models.FileField(blank=True, upload_to='uploads/')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
